### ISSUE TITLE
how to get golangci.yml config

### ISSUE THREAD

**Issue by greyireland** [dbraley/example-linter#1]
A costom linter how to get the .golangci.yml config？
example:
```
linters-settings:
  custom:
    mylint:
     path: /usr/local/bin/mylint.so
     description: The description of the linter
     original-url: github.com/golangci/example-linter
  mylint:
    max_lines: 80
    keywords: "TODO,BUG,FIX"
```
